### ISSUE TITLE
Expression (if,while) get command exit code '{ }' to support redirection to /dev/null or no output at all

### ISSUE THREAD

**Issue by c-pointer** [tcsh-org/tcsh#113]
I don't know if it is bug or enhancement but

This works
```
if ( { ping -c 1 -w 1 192.168.0.1 } ) then
  echo "LAN is up"
endif
```

This does not works (works but redirection does not)
```
if ( { ping -c 1 -w 1 192.168.0.1 >& /dev/null } ) then
  echo "LAN is up"
endif
```

**Comment by suominen** [comment]
Alternative approaches:
```
ping -c 1 -w 1 192.168.0.1 >& /dev/null && echo "LAN is up"
```
or
```
ping -c 1 -w 1 192.168.0.1 >& /dev/null
if ( $? == 0 ) then
  echo "LAN is up"
endif
```

**Comment by zoulasc** [comment]
Should be fixed now.

christos

**Comment by Krush206** [comment]
I tested the fix some months ago, @zoulasc. There still seems to be a problem remaining there, which I can't recall now. Anyhow, [here's my fix](https://github.com/Krush206/etcsh/commit/c9a7adf8f96c911276fa93b28543d63ec75927c7). Commands are re-parsed in expressions.

**Comment by Krush206** [comment]
This has always been a bug in tcsh and csh, @c-pointer. The best solution I can provide is to [fork into a FIFO file](https://stackoverflow.com/a/77391638/13243105). Better yet, [redirect the file descriptors present in the file system](https://stackoverflow.com/a/77679056/13243105). Christos' solution seems to work for redirections, though not for pipes. My provided solution fixes pipes, too.

**Comment by Krush206** [comment]
This has always been a bug in tcsh and csh, @c-pointer. The best solution I can provide is to [fork into a FIFO file](https://stackoverflow.com/a/77391638/13243105). Better yet, [redirect the file descriptors present in the file system](https://stackoverflow.com/a/77679056/13243105). Christos' solution seems to work for redirections, though not for pipes. [My provided solution](https://github.com/Krush206/etcsh/commit/c9a7adf8f96c911276fa93b28543d63ec75927c7) fixes pipes, too.

Note tcsh and csh are indirect forks of PWB and V6 shells. Either shells share the same issues.
